version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`hackiod.mooo.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    labels:
      - "traefik.http.routers.backend.rule=Host(`hackiod.mooo.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.rule=Host(`hackiod.mooo.com`) && PathPrefix(`/docs`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    restart: always

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=geddyprime@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    labels:
      - "traefik.http.routers.adminer.rule=Host(`db.hackiod.mooo.com`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=myresolver"
    restart: always

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-manager
    labels:
      - "traefik.http.routers.proxy-manager.rule=Host(`proxy.hackiod.mooo.com`)"
      - "traefik.http.services.proxy-manager.loadbalancer.server.port=81"
      - "traefik.http.routers.proxy-manager.entrypoints=websecure"
      - "traefik.http.routers.proxy-manager.tls=true"
      - "traefik.http.routers.proxy-manager.tls.certresolver=myresolver"
    ports:
      - "81:81"
      - "443:443"
    restart: always
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data

volumes:
  postgres_data:
  letsencrypt:
